name:                huha
version:             0.0.3
github:              "andschneider/huha"
license:             MIT
author:              "Andrew Schneider"
maintainer:          "example@example.com"
copyright:           "2021 Andrew Schneider"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A bare bones static site generator
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andschneider/huha#readme>

dependencies:
- base >= 4.7 && < 5
- text
- commonmark
- commonmark-extensions
- hspec
- directory
- filepath
- stache
- aeson
- megaparsec

library:
  source-dirs: src

executables:
  huha-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XOverloadedStrings
    dependencies:
    - huha

tests:
  huha-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huha
    - hspec
